# Generated by Django 4.0.5 on 2022-07-03 21:12

import apps.reservation.funtions
import apps.reservation.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_desktop', models.CharField(help_text='Escritorios disponibles', max_length=3, verbose_name='Available desktops')),
            ],
            options={
                'verbose_name': 'Desktop',
                'verbose_name_plural': 'Desktops',
                'ordering': ['n_desktop'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, help_text='Fecha actual', verbose_name='Current date')),
                ('start_hour', models.DateTimeField(default=django.utils.timezone.now, help_text='Hora de inicio de la reserva', verbose_name='Start time (YYYY-MM-DD, hh:mm:ss)')),
                ('finish_hour', models.DateTimeField(default=apps.reservation.funtions.default_end, help_text='Hora de finalización de la reserva', verbose_name='End time (YYYY-MM-DD, hh:mm:ss)')),
                ('n_hours', models.DecimalField(decimal_places=2, default=12, help_text='Número de horas reservadas', max_digits=5, validators=[apps.reservation.validators.validate_maxValue, apps.reservation.validators.validate_minValue], verbose_name='Reserve hours')),
                ('status', models.BooleanField(default=False, help_text='Estado de la reserva', verbose_name='Reserve status')),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.desktop')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['start_hour'],
            },
        ),
    ]
