# Generated by Django 4.0.5 on 2022-06-26 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_desktop', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Desktop',
                'verbose_name_plural': 'Desktops',
                'ordering': ['n_desktop'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_hours', models.SmallIntegerField(default=12, verbose_name='Cantidad de horas a reservar')),
                ('date_reservation', models.DateField(verbose_name='Reservation date')),
                ('date', models.DateField(auto_now=True)),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.desktop')),
                ('user', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['date_reservation'],
                'unique_together': {('desktop', 'date_reservation')},
            },
        ),
    ]
