# Generated by Django 4.0.5 on 2022-07-02 15:19

import apps.reservation.funtions
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='n_desktop',
            field=models.CharField(help_text='Escritorios disponibles', max_length=3, verbose_name='Available desktops'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='finish_hour',
            field=models.DateTimeField(default=apps.reservation.funtions.default_end, help_text='Hora de finalización de la reserva', verbose_name='End time (YYYY-MM-DD, hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_hour',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Hora de inicio de la reserva', verbose_name='Start time (YYYY-MM-DD, hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(default=False, help_text='Estado de la reserva', verbose_name='Reserve status'),
        ),
    ]
