# Generated by Django 4.0.5 on 2022-06-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_finish_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='finish_hour',
            field=models.DateTimeField(help_text='Hora de finalización de la reserva', verbose_name='End time (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_hour',
            field=models.DateTimeField(help_text='Hora de inicio de la reserva', verbose_name='Start time (hh:mm:ss)'),
        ),
    ]
