# Generated by Django 4.0.5 on 2022-06-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_finish_hour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['start_hour'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('desktop', 'start_hour', 'finish_hour')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation',
        ),
    ]
