# Generated by Django 4.0.5 on 2022-06-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_desktop', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Desktop',
                'verbose_name_plural': 'Desktops',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('None', 'None')], default=None, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('n_hours', models.SmallIntegerField(default=8, verbose_name='Cantidad de horas a reservar')),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encora_app.desktop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encora_app.user')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
