# Generated by Django 4.0.5 on 2022-06-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_desktop', models.CharField(max_length=3, verbose_name='Desktop')),
            ],
            options={
                'verbose_name': 'Desktop',
                'verbose_name_plural': 'Desktops',
                'ordering': ['n_desktop'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('None', 'None')], default=None, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_hours', models.SmallIntegerField(default=12, verbose_name='Number of hours to reserve')),
                ('date', models.DateField(auto_now=True)),
                ('date_reservation', models.DateField(verbose_name='Reservation date')),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encora_app.desktop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encora_app.user')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['date_reservation'],
            },
        ),
    ]
