# Generated by Django 4.0.5 on 2022-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmodel',
            old_name='birth_date',
            new_name='birthday',
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1, verbose_name='Which gender do you identify with?'),
        ),
    ]
