# Generated by Django 4.0.5 on 2022-06-29 20:27

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='username',
            field=models.CharField(error_messages={'único': 'Este nombre de usuario ya está en uso.'}, help_text='Nombre de usuario, Requerido. 150 caracteres o menos.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
        ),
    ]
